/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_game_Player */

#ifndef _Included_xreal_server_game_Player
#define _Included_xreal_server_game_Player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_game_Player
 * Method:    sendServerCommand
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_sendServerCommand
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_server_game_Player
 * Method:    getUserInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_server_game_Player_getUserInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setUserInfo
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setUserInfo
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_server_game_Player
 * Method:    getUserCommand
 * Signature: (I)Lxreal/UserCommand;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_Player_getUserCommand
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_commandTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1commandTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_commandTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1commandTime
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_pm_type
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1pm_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_type
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1type
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_pm_flags
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1pm_1flags
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_flags
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1flags
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_pm_time
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1pm_1time
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_pm_time
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1pm_1time
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_bobCycle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1bobCycle
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_bobCycle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1bobCycle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_origin
 * Signature: (I)Ljavax/vecmath/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_Player_getPlayerState_1origin
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_origin
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1origin
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_velocity
 * Signature: (I)Ljavax/vecmath/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_Player_getPlayerState_1velocity
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_velocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1velocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_weaponTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1weaponTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_weaponTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1weaponTime
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_gravity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1gravity
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_gravity
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1gravity
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_speed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1speed
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_speed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1speed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_deltaPitch
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_xreal_server_game_Player_getPlayerState_1deltaPitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_deltaPitch
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1deltaPitch
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_deltaYaw
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_xreal_server_game_Player_getPlayerState_1deltaYaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_deltaYaw
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1deltaYaw
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_deltaRoll
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_xreal_server_game_Player_getPlayerState_1deltaRoll
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_deltaRoll
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1deltaRoll
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_groundEntityNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1groundEntityNum
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_groundEntityNum
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1groundEntityNum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_legsTimer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1legsTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_legsTimer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1legsTimer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_legsAnim
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1legsAnim
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_legsAnim
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1legsAnim
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_torsoTimer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1torsoTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_torsoTimer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1torsoTimer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_torsoAnim
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1torsoAnim
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_torsoAnim
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1torsoAnim
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_movementDir
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1movementDir
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_movementDir
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1movementDir
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_grapplePoint
 * Signature: (I)Ljavax/vecmath/Vector3f;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_Player_getPlayerState_1grapplePoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_grapplePoint
 * Signature: (ILjavax/vecmath/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1grapplePoint
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_eFlags
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1eFlags
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_eFlags
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1eFlags
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_eventSequence
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1eventSequence
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_eventSequence
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1eventSequence
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_externalEvent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1externalEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_externalEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1externalEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_externalEventParm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1externalEventParm
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_externalEventParm
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1externalEventParm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_externalEventTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1externalEventTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_externalEventTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1externalEventTime
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_weapon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1weapon
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_weapon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1weapon
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_weaponState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1weaponState
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_weaponState
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1weaponState
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_viewAngles
 * Signature: (I)Lxreal/Angle3f;
 */
JNIEXPORT jobject JNICALL Java_xreal_server_game_Player_getPlayerState_1viewAngles
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_viewAngles
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1viewAngles
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_viewHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1viewHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_viewHeight
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1viewHeight
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_damageEvent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1damageEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_damageEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1damageEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_damageYaw
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1damageYaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_damageYaw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1damageYaw
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_damagePitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1damagePitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_damagePitch
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1damagePitch
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_damageCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1damageCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_damageCount
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1damageCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_generic1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1generic1
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_generic1
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1generic1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_loopSound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1loopSound
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_loopSound
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1loopSound
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_jumppad_ent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1jumppad_1ent
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_jumppad_ent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1jumppad_1ent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_ping
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1ping
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_ping
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1ping
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    getPlayerState_stat
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xreal_server_game_Player_getPlayerState_1stat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xreal_server_game_Player
 * Method:    setPlayerState_stat
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_xreal_server_game_Player_setPlayerState_1stat
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
