/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xreal_server_Server */

#ifndef _Included_xreal_server_Server
#define _Included_xreal_server_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xreal_server_Server
 * Method:    getConfigString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xreal_server_Server_getConfigString
  (JNIEnv *, jclass, jint);

/*
 * Class:     xreal_server_Server
 * Method:    setConfigString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_Server_setConfigString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     xreal_server_Server
 * Method:    broadcastServerCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xreal_server_Server_broadcastServerCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
